### ISSUE TITLE
Which file?

### ISSUE THREAD

**Issue by BOsterbuhr** [BOsterbuhr/FEC-Data-Wranglin#11]
Structure wise, where should this go?

https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/5e9adb88c2797994cfcb9275d01b1b346fe6e8a2/get_that_data.py#L10-L41

Also,
https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/5e9adb88c2797994cfcb9275d01b1b346fe6e8a2/get_that_data.py#L36 

Where would this be saved? `/data` is my guess.

What is the difference in the `/data` and `/src/data`? What is your idea for what goes in `/src/analysis`?

Ok I think that's it for now, more later I assume.

**Comment by NapsterInBlue** [comment]
More good questions!

For starters, you very, very rarely want to push a .csv up to GitHub. Reproducibility is the gold standard when you're doing Data Work. Ideally, you should be able to blow away all of your data, hit "run", and get your entire project/model back exactly how it was before. Which reminds me-- I need to update the `.gitignore` file at the root (this essentially says "don't monitor files that look like ___" and prevents you from accidentally committing junk to the project).

So

The `/data/` folder in the root is where we're going to write all of our `.csv`,  `.pkl`, `.json`, whatever files. You'll notice that there's a `.gitkeep` file here. Unlike `.gitignore`, which does special stuff, `.gitkeep` doesn't do anything at all-- it's just convention that you use when you want to preserve a directory structure. If I'd left `/data/` empty, Git wouldn't pick it up, because it doesn't bother tracking anything that's empty. So we just `touch data/.gitkeep` to drop a blank file there and get it on Git's radar.

On the other hand, we have `/src/data/`. `src` is just convention for **S**ou**RC**e code. Often you might also see this be the name of the repo, again (e.g. if you clone [pandas](https://github.com/pandas-dev/pandas), you'll have a directory called `pandas/pandas` on your computer). Then the `/src/data/` directory makes a *submodule* (`from src.data import ...`) where we'll park all of our code that deals with moving data around.

As far as `/src/analysis` this could be anything. I just wanted to put another folder there to inspire the "refactor useful code out of your notebook" that [Jake gets to in step 5 of his series](https://www.youtube.com/watch?v=_ZEWDGpM-vM) (seriously, give this a watch, it's excellent)

-----

Now, addressing your first question, I see two chunks of code here:

1. Transform our big'ol `list` into a `DataFrame`. This should get worked into the `DataFetcher` class-- probably as a `_build_df()` function that leverages `self.complete_list` at the end of a `gimmie_data()` call.
2. Serialization (a $2 word for "build into a standardized format"). This would take our `DataFrame` and handle writing it to `/data/`. We could also get clever and write it as a `.csv`, generating the filename from the arguments to `gimmie_data()`

Where we go from there really depends on your use-case!

**Comment by BOsterbuhr** [comment]
OK I am broken, I can't push to the branch big_refactor_testin because it doesn't exist anymore. So how do I push my commit to a new branch?

**Comment by BOsterbuhr** [comment]
Ok I think I forced things to work but I have no idea how, definitely messed up my git structure locally

**Comment by NapsterInBlue** [comment]
Ah, my apologies. I should have been more explicit about what I thought the workflow would be.

I tend to follow something like a [Feature Branch Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow), and figured since we were done adding the first tests to the `big_refactor` branch we could close it.

Haven't actually read/tried the new code yet, but I think repeating the "branch off of the latest version of `big_refactor` as `big_refactor_save_data` might have been more appropriate
