### ISSUE TITLE
remove this

### ISSUE THREAD

**Issue by BOsterbuhr** [BOsterbuhr/FEC-Data-Wranglin#8]
https://github.com/BOsterbuhr/FEC-Data-Wranglin/blob/e0ce967e2fd68f9b9d61ce415d5717c30a801e59/src/data/data_fetcher.py#L266

**Comment by NapsterInBlue** [comment]
More than happy to merge these edits! And it's good practice, for that matter!

I'm assuming you're using GitHub, and not the command line (which I'd solidly recommend practicing with, by the by. It's what I use, exclusively). So why don't you switch to the `big_refactor` branch, and make a new branch *off of that branch*. Something like

![image](https://user-images.githubusercontent.com/3505365/101262690-85df3600-370e-11eb-8d8e-bb7e982ce0ca.png)

Then you can go into the files for this issue, as well as #7 , #3 , #6, and #5 , make the edits, commit them, and then submit a Pull Request back onto the `big_refactor` branch by 

1. Clicking on Pull Requests

![image](https://user-images.githubusercontent.com/3505365/101262738-d9ea1a80-370e-11eb-9acb-698929da2578.png)

2. Click New Pull Request

![image](https://user-images.githubusercontent.com/3505365/101262750-ea01fa00-370e-11eb-8a2c-308015555196.png)

3. Setting it up so that your new branch (B) gets pulled into `big_refactor` (A)

![image](https://user-images.githubusercontent.com/3505365/101262774-0c941300-370f-11eb-9df2-14fa60692f16.png)

Doing so will create a new Pull Request, and a new thread where we can do a more-formal code review, and merge the code in.

**Comment by BOsterbuhr** [comment]
Ok awesome I will try all of this and see what happens. First a quick nap while the kid is napping.

**Comment by NapsterInBlue** [comment]
Take your time, pal. Just trying to set you up with good practice stuff while I've got the time to do so :)
